### ISSUE TITLE
[Error] Cast from pointer to smaller type 'unsigned int' loses information

### ISSUE THREAD

**Issue by bitorangej** [gxf1027/randomforests#1]
报错位于 `SharedRoutines.cpp` 文件第197行

<img width="1233" alt="Snipaste_2024-01-26_15-39-07" src="https://github.com/gxf1027/randomforests/assets/96936298/4b7f883a-3ff6-42c4-ae2a-13415e26299c">

**Comment by gxf1027** [comment]
g++ -std=c++11 -fpermissive -O2 src/RandomRLoquatForests.cpp src/SharedRoutines.cpp src/UserInteraction2.cpp src/RandomCLoquatForests.cpp src/tinyxml2/tinyxml2.cpp demo/rf_train.cpp -o rf_train

**Comment by gxf1027** [comment]
g++ -std=c++11 -fpermissive -O2 src/RandomRLoquatForests.cpp src/SharedRoutines.cpp src/UserInteraction2.cpp src/RandomCLoquatForests.cpp src/tinyxml2/tinyxml2.cpp demo/rf_train.cpp -o rf_train  无法重现以上问题。另，可以先注释kcfAlloc, kcfFree函数解决。
